### ISSUE TITLE
Error when trying to serialize a Int64

### ISSUE THREAD

**Issue by ricklesauceur** [aaulia/msgpack-haxe#11]
I try to serialize Int64 using the library and it just fails with this error:
`Error: haxe._Int64.___Int64 not supported`

The int64 declaration is :
`public var ID:haxe.Int64 = 0;`

The comparison in Encoder.hx seems to be never triggered.
`case "haxe.Int64"  : writeInt64(d);`

Cheers

**Comment by aaulia** [comment]
Hmm weird, what target is this? The class name should be haxe.Int64.

**Comment by ricklesauceur** [comment]
Flash and js

**Comment by aaulia** [comment]
Okay I'll take a look at it.
