### ISSUE TITLE
Use non-deprecated Int64 (high/low) member fields.

### ISSUE THREAD

**Issue by dionjwa** [aaulia/msgpack-haxe#14]
...haxelib/msgpack-haxe/1,15,0/org/msgpack/Encoder.hx:54: characters 15-31 : Warning : Use high instead
...haxelib/msgpack-haxe/1,15,0/org/msgpack/Encoder.hx:55: characters 15-30 : Warning : Use low instead

I don't like seeing the warnings on every compile :-)

**Comment by aaulia** [comment]
Just release a patch version 1.15.1. Should fix it.
