### ISSUE TITLE
Not available on haxelib

### ISSUE THREAD

**Issue by Richard-Walton** [aaulia/msgpack-haxe#2]
I tried installing your library using `haxelib install msgpack-haxe` and was told that there was `No such Project : msgpack-haxe`.

**Comment by Type1J** [comment]
@aaulia Please do add it to haxelib. If it's out of date, then we (the users of msgpack-haxe) will give you pull requests to update it as we need it, but having it on haxelib makes it much more convenient.

**Comment by aaulia** [comment]
Soo I tried submiting the latest commit to haxelib, it seems haxelib must know all user involved. Right now it complained that it doesn't know @Type1J . I'll try again tomorrow, and ask around about it.

**Comment by aaulia** [comment]
I added it to haxelib as msgpack-haxe. I only did minimal testing (using the example and haxelib dev) but hopefully everything should be okay.

@Type1J please add yourself to haxelib so I can put you on the contributors again, since haxelib would not accept the zip if it contain unregistered user.

**Comment by Type1J** [comment]
@aaulia I added myself to haxelib. Sorry about that, I should have done that a while ago.
