### ISSUE TITLE
Maps with non-string keys 

### ISSUE THREAD

**Issue by mcheshkov** [aaulia/msgpack-haxe#4]
In current implementation it's not possible to use other type than String - map is represented as StringMap or Dynamic, where field names is also strings. While msgpack spec allows keys to be any type, even different types. So most appropriate structure is array/list of key-value pairs with possible conversion to usual maps.

Actually, I ran into this because we use int as keys, so possible solution is to implement IntMap handling in encode, and to check first element type in readMap in !obj case.

I can make it, and send PR. What do you think?

**Comment by aaulia** [comment]
Please do, I'll take a look at it.
